name: media_picker
description: A new Flutter package for accessing medias in storage.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  photo_manager: ^3.1.1
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  bottom_sheet: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

